### ISSUE TITLE
Fix issues from the doc

### ISSUE THREAD

**Issue by tomesfilip** [tomesfilip/culturea-2024-astro#12]
1. datum: 3. dubna 2024
2. 14/15 Baťův institut kavárna, Zlín
3. mapa krajin: někde jsou v mapě u jednoho ročníku uvedeny obě země, jinde jen jedna - prosím sjednotit
když najedu myší na Brazílii, tak mi to zemi/země nezobrazí a problikává to - háže to chybu (někdy i u jiných zemí)
4. KONTAKTY - osobné univerzitné maily zmeniť na maily sekcií + doupraviť názvy “pozícií” tam, kde je to inak, pri holkách doplniť manažerKA a pod..  (tak, ako sme napísali pri [manažérskych fotkách na disku](https://drive.google.com/drive/u/0/folders/1-KmCZ-cTL7pwekB2mTqyDNB6vU7G_-hr))
5. Odstranit závorku a její obsah – (PŘI JEJÍ NÁVŠTĚVĚ ŽÁDNÝ TURISTA NEOPOMENE NAVŠTÍVIT PROMENÁDU MALECÓN NEBO NÁMĚSTÍ HABANA VIEJA.) – u textu u Kuby

**Comment by WilloS88** [comment]
Everything done except 3.
